# syntax=docker/dockerfile:1

### Build 
FROM golang:1.18-alpine AS build
WORKDIR /app
COPY ./ ./
RUN go mod download
WORKDIR /app/cmd
RUN CGO_ENABLED=0 go build -buildvcs=false -o urlshortener

### Deploy
FROM scratch
WORKDIR /
COPY --from=build /app/cmd/urlshortener .
EXPOSE 8081
ENTRYPOINT ["./urlshortener"]